begin;

create table if not exists public.postype_search_events (
  id bigint generated by default as identity primary key,
  searched_at timestamptz not null default now(),
  searched_on date not null default ((now() at time zone 'Asia/Seoul')::date),
  query_text text not null,
  query_kind text not null check (query_kind in ('text', 'filter')),
  result_count integer not null default 0 check (result_count >= 0),
  session_id text,
  path text
);

create index if not exists postype_search_events_date_idx on public.postype_search_events (searched_on desc, searched_at desc);
create index if not exists postype_search_events_query_idx on public.postype_search_events (query_kind, query_text, searched_on desc);
alter table public.postype_search_events enable row level security;

drop policy if exists postype_search_events_public_insert on public.postype_search_events;
create policy postype_search_events_public_insert on public.postype_search_events for insert to anon, authenticated
with check (
  char_length(query_text) between 1 and 500
  and query_kind in ('text', 'filter')
  and result_count between 0 and 1000000
  and char_length(coalesce(session_id, '')) <= 80
  and char_length(coalesce(path, '')) <= 500
);

revoke all on public.postype_search_events from anon, authenticated;
grant insert on public.postype_search_events to anon, authenticated;
grant usage, select on sequence public.postype_search_events_id_seq to anon, authenticated;

create or replace function public.postype_admin_search_stats(p_from date, p_to date, p_limit integer default 20)
returns jsonb language sql stable security definer set search_path = public as $$
  with filtered as (
    select * from public.postype_search_events
    where searched_on between least(p_from, p_to) and greatest(p_from, p_to)
  ), top_queries as (
    select query_kind, query_text, count(*)::bigint searches,
      count(distinct session_id)::bigint visitors,
      count(*) filter (where result_count = 0)::bigint zero_results,
      max(searched_at) last_searched_at
    from filtered group by query_kind, query_text
    order by searches desc, last_searched_at desc
    limit least(greatest(p_limit, 1), 20)
  ), recent as (
    select searched_at, searched_on, query_kind, query_text, result_count
    from filtered order by searched_at desc limit 100
  )
  select jsonb_build_object(
    'totals', jsonb_build_object(
      'searches', (select count(*) from filtered),
      'visitors', (select count(distinct session_id) from filtered),
      'zeroResults', (select count(*) from filtered where result_count = 0)
    ),
    'top', coalesce((select jsonb_agg(to_jsonb(top_queries) order by searches desc, last_searched_at desc) from top_queries), '[]'::jsonb),
    'recent', coalesce((select jsonb_agg(to_jsonb(recent) order by searched_at desc) from recent), '[]'::jsonb)
  );
$$;

revoke all on function public.postype_admin_search_stats(date, date, integer) from public, anon, authenticated;
grant execute on function public.postype_admin_search_stats(date, date, integer) to service_role;

commit;
